syntax = "proto3";

package common.metadata.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/amirhossein-shakeri/zhinux-contracts/gen/go/common/metadata/v1;metadatav1";

// Standard metadata structure
message Metadata {
  // Represents the unique identifier
  string id = 1;

  // Represents the creation time
  google.protobuf.Timestamp created_at_unix = 2;

  // Represents the latest modification time
  google.protobuf.Timestamp updated_at_unix = 3;

  // Represents the deletion(soft) time, if applicable
  google.protobuf.Timestamp deleted_at_unix = 4;
}
